version: '3'

services:
  gotify:
    image: gotify/server
    ports:
      - 9000:80
    environment:
      GOTIFY_DEFAULTUSER_PASS: 'admin'
    volumes:
      - gotify_data:/app/data
    # to run gotify as a dedicated user:
    # user: "1234:1234"

volumes:
  gotify_data:
